name: Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env: 
  DOCKER_REPOSITORY: meetcw/clash-with-dashboard

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
      
    - name: Docker Login
      uses: docker/login-action@v1.13.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Create Docker image tag
      run: echo DATE_TAG=$(date +%y%m%d%H%M%S) >> $GITHUB_ENV
      
    - name: Push the Docker image
      uses: docker/build-push-action@v2.9.0
      with:
        push: true
        tags: |
          ${{ env.DOCKER_REPOSITORY }}:${{ env.DATE_TAG }}
          ${{ env.DOCKER_REPOSITORY }}:latest
        
